name: neoPaintingSwitch
main: plugin.arcwolf.neopaintingswitch.neoPaintingSwitch
version: 1.4
api-version: 1.19
softdepend: [PlotSquared,WorldEdit,WorldGuard]
permissions:
    neopaintingswitch.*:
        description: Wildcard option for comfort.
        children:
            neopaintingswitch.use: true
            neopaintingswitch.bypass: true
    neopaintingswitch.use:
        description: Allows the user to scroll through paintings.
        default: op
    neopaintingswitch.bypass:
        description: Allows the user to bypass painting permissions based on plots or regions.
        default: op